version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: epu-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: epugestao123
      MONGO_INITDB_DATABASE: epu_gestao
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - epu-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: epu-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      DB_URI: mongodb://admin:epugestao123@mongodb:27017/epu_gestao?authSource=admin
      JWT_SECRET: epu-gestao-jwt-secret-key-super-secure-2025
      CORS_ORIGIN: http://localhost:3000
    ports:
      - '5000:5000'
    depends_on:
      - mongodb
    volumes:
      - ./backend/src:/app/src
      - ./backend/package.json:/app/package.json
    networks:
      - epu-network

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: epu-frontend
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
      REACT_APP_ENV: production
    ports:
      - '3000:3000'
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    networks:
      - epu-network

volumes:
  mongodb_data:
    driver: local

networks:
  epu-network:
    driver: bridge
